export const SAVE_FAVORITES = "SAVE_FAVORITES";

export const SAVE_IDX = "SAVE_IDX";

export const TOGGLE_FAVORITES_MODE = "TOGGLE_FAVORITES_MODE";

export const SAVE_SHUFFLE_LIST = "SAVE_SHUFFLE_LIST";

export const TOGGLE_SHUFFLE_MODE = "TOGGLE_SHUFFLE_MODE";
