export const REGISTER_FIREBASE_SUCCESS = "REGISTER_FIREBASE_SUCCESS";

export const SAVE_CREATE_ACC_FORM = "SAVE_CREATE_ACC_FORM";

export const SAVE_USER_PREF = "SAVE_USER_PREF";

export const REGISTER_HIRO_USER_SUCCESS = "REGISTER_HIRO_USER_SUCCESS";
