export const SPOTIFY_INITIALIZE_SUCCESS = "SPOTIFY_INITIALIZE_SUCCESS";

export const SPOTIFY_INITIALIZE_FAIL = "SPOTIFY_INITIALIZE_FAIL";

export const SPOTIFY_LOGIN = "SPOTIFY_LOGIN";

export const SPOTIFY_LOGOUT = "SPOTIFY_LOGOUT";
