export const SPOTIFY_INITIALIZE_SUCCESS = "SPOTIFY_INITIALIZE_SUCCESS";

export const SPOTIFY_INITIALIZE_FAIL = "SPOTIFY_INITIALIZE_FAIL";

export const SPOTIFY_LOGIN = "SPOTIFY_LOGIN";

export const SPOTIFY_LOGOUT = "SPOTIFY_LOGOUT";

export const CHANGE_PLAY_STATUS = "CHANGE_PLAY_STATUS";

export const SAVE_TRACK_METADATA = "SAVE_TRACK_METADATA";

export const SAVE_CURRENT_POSITION = "SAVE_CURRENT_POSITION";
